# Generated by Django 5.2.3 on 2026-08-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('short_video', 'Short Video (1-10 mins)'), ('long_video', 'Long Video (2+ hrs)'), ('pdf', 'PDF Blueprint / Document')], default='short_video', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='content/')),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('duration', models.CharField(default='45 mins', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Master the Art of Landscape Architecture', max_length=255)),
                ('hero_subtitle', models.TextField(default='Elevate your architectural vision. Access industry-leading video modules, spatial planning frameworks, and achieve complete mastery.')),
                ('logo_size', models.IntegerField(default=48)),
                ('logo_fit_mode', models.CharField(default='auto', max_length=20)),
                ('course_price', models.DecimalField(decimal_places=2, default=499.0, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Vid',
        ),
        migrations.AddField(
            model_name='usr',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
