# Generated by Django 5.2.3 on 2026-08-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_category_slug_alter_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='logo_url',
            field=models.TextField(default='/lm_logo.png'),
        ),
    ]
