# Generated by Django 5.2.3 on 2026-08-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_sitesetting_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='curriculum_pdf_size',
            field=models.CharField(default='4.2 MB', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='curriculum_pdf_title',
            field=models.CharField(default='Landscape Architecture Masterclass Curriculum & Blueprint Guide 2026', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='curriculum_pdf_url',
            field=models.TextField(default='/media/Landscape_Architecture_Syllabus_2026.pdf'),
        ),
    ]
