# Generated by Django 5.2.17 on 2026-09-19 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_sitesetting_curriculum_pdf_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.course'),
        ),
    ]
